version: "3.7"

volumes:
  voice_data: 
    name: "voice_data"

services:
  backend: &backend
    container_name: cloud_backend
    image: local_cloud_backend
    build:
      context: backend
      dockerfile: compose/development/app/Dockerfile
    env_file:
      - backend/env/development/app
      - backend/env/development/postgres
    volumes:
      - voice_data:/app/wsgi.py
      - voice_data:/app/src
      - voice_data:/app/cloud_1.db
    ports:
      - 5000:5000
    command: /app/start

  celery_worker:
    <<: *backend
    image: local_cloud_celery_worker
    container_name: cloud_celery_worker
    depends_on:
      - redis
    ports: []
    command: /app/celery_worker_start

  celery_beat:
    <<: *backend
    image: local_cloud_celery_beat
    container_name: cloud_celery_beat
    depends_on:
      - redis
    ports: []
    command: /app/celery_beat_start

  redis:
    image: redis
    container_name: cloud_redis